name: publish

on:
  push:
    branches:    
      - master

env:
  GO_VERSION: "1.16"

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build go binary
        run: make build
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.QUAY_IO_USER }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      - name: Build and Push docker image
        run: |
          docker build --pull --tag ghcr.io/git-chglog/git-chglog:edge .
          docker push ghcr.io/git-chglog/git-chglog:edge
